---
title: "Assessing and Mitigating Algorithmic Bias in Criminal Risk Scores"
author: "Lucius Bynum, Preethi Seshadri"
date: '19 November 2017'
# output:
  # html_document:
  #   theme: journal
  #   highlight: tango
  #   df_print: paged
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message=FALSE, warning=FALSE, cache=TRUE)
options(digits=4)

library(dplyr)
library(GGally)
library(ggplot2)
library(e1071)
library(caret)
```

## Our Logistic Regression Model

### Variable Selection

```{r}
compas_data <- read.csv('compas-scores-two-years.csv')
```

Clean the compas dataset using the same approach Propublica uses. 
```{r}
compas_data <- compas_data %>%
  select(age, c_charge_degree, race, age_cat, score_text, sex, priors_count, days_b_screening_arrest, decile_score, is_recid, two_year_recid, c_jail_in, c_jail_out) %>% 
  filter(days_b_screening_arrest <= 30) %>%
  filter(days_b_screening_arrest >= -30) %>%
  filter(is_recid != -1) %>%
  filter(c_charge_degree != "O") %>%
  filter(score_text != 'N/A')
```


We will include the time spent in jail (scaled to be in days).
```{r}
compas_data$c_jail_out <- strptime(compas_data$c_jail_out, format = '%Y-%m-%d %H:%M:%S')
compas_data$c_jail_in <- strptime(compas_data$c_jail_in, format = '%Y-%m-%d %H:%M:%S')
compas_data$time_spent <- difftime(compas_data$c_jail_out, compas_data$c_jail_in, units='days')
compas_data$time_spent <- as.numeric(compas_data$time_spent)
compas_data <- compas_data[, !(colnames(compas_data) %in% c("c_jail_out", "c_jail_in"))]
```

We will remove examples that do not have a time spent in jail value.
```{r}
compas_data <- compas_data[!is.na(compas_data$time_spent),]
```

```{r}
# perform k-fold cross validation
compas_data <- compas_data[sample(1:nrow(compas_data)), ] # shuffle the rows up
folds <- cut(seq(1,nrow(compas_data)),breaks=10,labels=FALSE) # divide into 10 folds
#Perform 10 fold cross validation
matrices <- list()
race_bias <- c()
sex_bias <- c()
age_bias <- c()
for(i in 1:10) { # loop through each fold and fit model
  vars <- compas_data %>% select(sex, age, ends_with('count'), c_charge_degree, time_spent, is_recid)
  indices <- which(folds==i,arr.ind=TRUE) 
  testData <- vars[indices, ] 
  trainData <- vars[-indices, ] 
  compas_test <- compas_data[indices, ]
  
  # fit a logistic regression model on training data to predict recidivism
  model <- glm(is_recid ~., family = binomial(link='logit'), data = trainData)
  
  # compute predictions and confusion matrix
  preds <- predict(model, newdata = testData, type = "response") # response gives probability instead of log odds
  matrices[[i]] <- confusionMatrix(data = as.numeric(preds>0.5), reference = testData$is_recid)
  
  # compute low, medium, high scores
  our_scores <- compas_test %>%
  mutate(new_score = preds) %>%
  mutate(new_score_text = as.factor(
      ifelse(new_score >= 0.75, 'High',
             ifelse(new_score >= 0.45, 'Medium', 'Low')))
  )
  
  # create a new dataframe for predicting probability of recidivating (as specified by our model)
  new_df <- our_scores %>%
    mutate(crime_factor = factor(c_charge_degree)) %>%
    mutate(age_factor = as.factor(age_cat)) %>%
    within(age_factor <- relevel(age_factor, ref = 1)) %>%
    mutate(race_factor = factor(race)) %>%
    within(race_factor <- relevel(race_factor, ref = 3)) %>%
    mutate(gender_factor = factor(sex, labels= c("Female","Male"))) %>%
    within(gender_factor <- relevel(gender_factor, ref = 2)) %>%
    mutate(score_factor = factor(new_score_text != "Low", labels = c("LowScore","HighScore")))
  
  # new logistic regression model to predict our computed recidivism probabilities (on the test data)
  new_pp_model <- glm(score_factor ~ gender_factor + age_factor + race_factor + priors_count + crime_factor + two_year_recid, family="binomial", data=new_df)
  
  model_intercept <- coef(new_pp_model)['(Intercept)']
  # Bias race
  black_coef <- coef(new_pp_model)['race_factorAfrican-American']
  race_bias[i] <- (sigmoid(model_intercept + black_coef) / sigmoid(model_intercept))
  
  # Bias sex
  woman_coef <- coef(new_pp_model)['gender_factorFemale']
  sex_bias[i] <- (sigmoid(model_intercept + woman_coef) / sigmoid(model_intercept))
  
  # Bias age
  age_coef <- coef(new_pp_model)['age_factorLess than 25']
  age_bias[i] <- (sigmoid(model_intercept + age_coef) / sigmoid(model_intercept))
}
```

```{r}
matrices
race_bias
sex_bias
age_bias
````